---
stages:
  - lint
  - test

lint-job:
  script:
    - npm install
    - npm run lint
  stage: lint
  tags:
    - attendance

test-job:
  script:
    - npm install
    - npm run test
  stage: test
  tags:
    - attendance
